name: blog_bloc_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.6.0-216.1.beta

dependencies:
    dotted_border: ^2.1.0
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.6
    fpdart: ^1.1.1
    get_it: ^8.0.2
    go_router: ^14.6.1
    hive: ^4.0.0-dev.2
    image_picker: ^1.1.2
    internet_connection_checker_plus: ^2.5.2
    intl: ^0.20.1
    isar_flutter_libs: ^4.0.0-dev.13
    path_provider: ^2.0.0
    supabase_flutter: ^2.8.1
    uuid: ^4.5.1

dev_dependencies:
    flutter_lints: ^5.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
